---
- name: Install and configure PostgreSQL HA.
  hosts: all
  become: true

  roles:
    - consul
    - dnsmasq
    - postgres

- name: Install and initializing Pantroni.
  hosts: all
  become: true
  serial: 1

  roles:
    - patroni