---
- name: Install the postgresql rpm from a remote repo.
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install dependencies.
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - postgresql12
    - postgresql12-server

